name: Java CI

on:
  push:
    branches: [ main ] # Defina a branch onde deseja executar os testes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Versão do Java que você está utilizando

    - name: Build with Maven and run tests
      run: mvn -B test # Comando para executar os testes com Maven
